spring.application.name=preparcialfifa

# H2
spring.datasource.url=jdbc:h2:mem:testDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA crea las tablas desde tus @Entity
spring.jpa.hibernate.ddl-auto=create-drop

# IMPORTANTE:
# primero Hibernate crea las tablas y luego se ejecuta data.sql
spring.jpa.defer-datasource-initialization=true

# ejecutar data.sql
spring.sql.init.mode=always

# para ver SQL en consola
spring.jpa.show-sql=true

# consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console